// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ui_message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ui_message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace indigo {
namespace pb {

void protobuf_ShutdownFile_ui_5fmessage_2eproto() {
  delete ui_message::default_instance_;
}

void protobuf_AddDesc_ui_5fmessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::indigo::pb::protobuf_AddDesc_indigo_5fmessage_2eproto();
  ui_message::default_instance_ = new ui_message();
  ui_message::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::indigo::pb::indigo_msg::default_instance(),
    200, 11, false, false,
    &::indigo::pb::ui_message::default_instance());
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::indigo::pb::internal_msg::default_instance(),
    200, 11, false, false,
    &::indigo::pb::ui_message::default_instance());
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ui_5fmessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ui_5fmessage_2eproto {
  StaticDescriptorInitializer_ui_5fmessage_2eproto() {
    protobuf_AddDesc_ui_5fmessage_2eproto();
  }
} static_descriptor_initializer_ui_5fmessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ui_message::kDataFieldNumber;
#endif  // !_MSC_VER

#ifndef _MSC_VER
const int ui_message::kUiMessageOutFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::indigo::pb::indigo_msg,
    ::google::protobuf::internal::MessageTypeTraits< ::indigo::pb::ui_message >, 11, false >
  ui_message::ui_message_out(kUiMessageOutFieldNumber, ::indigo::pb::ui_message::default_instance());
#ifndef _MSC_VER
const int ui_message::kUiMessageInFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::indigo::pb::internal_msg,
    ::google::protobuf::internal::MessageTypeTraits< ::indigo::pb::ui_message >, 11, false >
  ui_message::ui_message_in(kUiMessageInFieldNumber, ::indigo::pb::ui_message::default_instance());
ui_message::ui_message()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:indigo.pb.ui_message)
}

void ui_message::InitAsDefaultInstance() {
}

ui_message::ui_message(const ui_message& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:indigo.pb.ui_message)
}

void ui_message::SharedCtor() {
  _cached_size_ = 0;
  data_ = 2;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ui_message::~ui_message() {
  // @@protoc_insertion_point(destructor:indigo.pb.ui_message)
  SharedDtor();
}

void ui_message::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ui_message::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ui_message& ui_message::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ui_5fmessage_2eproto();
  return *default_instance_;
}

ui_message* ui_message::default_instance_ = NULL;

ui_message* ui_message::New() const {
  return new ui_message;
}

void ui_message::Clear() {
  data_ = 2;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool ui_message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:indigo.pb.ui_message)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 data = 2 [default = 2];
      case 2: {
        if (tag == 16) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &data_)));
          set_has_data();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:indigo.pb.ui_message)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:indigo.pb.ui_message)
  return false;
#undef DO_
}

void ui_message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:indigo.pb.ui_message)
  // optional int32 data = 2 [default = 2];
  if (has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->data(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:indigo.pb.ui_message)
}

int ui_message::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 data = 2 [default = 2];
    if (has_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->data());
    }

  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ui_message::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ui_message*>(&from));
}

void ui_message::MergeFrom(const ui_message& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_data()) {
      set_data(from.data());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void ui_message::CopyFrom(const ui_message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ui_message::IsInitialized() const {

  return true;
}

void ui_message::Swap(ui_message* other) {
  if (other != this) {
    std::swap(data_, other->data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.swap(other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string ui_message::GetTypeName() const {
  return "indigo.pb.ui_message";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace indigo

// @@protoc_insertion_point(global_scope)
