// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events_message.proto

#ifndef PROTOBUF_events_5fmessage_2eproto__INCLUDED
#define PROTOBUF_events_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_util.h>
#include "indigo_message.pb.h"
// @@protoc_insertion_point(includes)

namespace indigo {
namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_events_5fmessage_2eproto();
void protobuf_AssignDesc_events_5fmessage_2eproto();
void protobuf_ShutdownFile_events_5fmessage_2eproto();

class indigo_event;

enum indigo_event_type {
  EVENT_NOTHING = 0
};
bool indigo_event_type_IsValid(int value);
const indigo_event_type indigo_event_type_MIN = EVENT_NOTHING;
const indigo_event_type indigo_event_type_MAX = EVENT_NOTHING;
const int indigo_event_type_ARRAYSIZE = indigo_event_type_MAX + 1;

// ===================================================================

class indigo_event : public ::google::protobuf::MessageLite {
 public:
  indigo_event();
  virtual ~indigo_event();

  indigo_event(const indigo_event& from);

  inline indigo_event& operator=(const indigo_event& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const indigo_event& default_instance();

  void Swap(indigo_event* other);

  // implements Message ----------------------------------------------

  inline indigo_event* New() const { return New(NULL); }

  indigo_event* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const indigo_event& from);
  void MergeFrom(const indigo_event& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(indigo_event* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .indigo.pb.indigo_event_type type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::indigo::pb::indigo_event_type type() const;
  void set_type(::indigo::pb::indigo_event_type value);

  // optional int32 time = 2;
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 2;
  ::google::protobuf::int32 time() const;
  void set_time(::google::protobuf::int32 value);

  // optional int32 parameter = 3;
  bool has_parameter() const;
  void clear_parameter();
  static const int kParameterFieldNumber = 3;
  ::google::protobuf::int32 parameter() const;
  void set_parameter(::google::protobuf::int32 value);

  static const int kEventsFieldNumber = 101;
  static ::google::protobuf::internal::ExtensionIdentifier< ::indigo::pb::indigo_msg,
      ::google::protobuf::internal::RepeatedMessageTypeTraits< ::indigo::pb::indigo_event >, 11, false >
    events;
  static const int kEventsInFieldNumber = 101;
  static ::google::protobuf::internal::ExtensionIdentifier< ::indigo::pb::internal_msg,
      ::google::protobuf::internal::RepeatedMessageTypeTraits< ::indigo::pb::indigo_event >, 11, false >
    events_in;
  // @@protoc_insertion_point(class_scope:indigo.pb.indigo_event)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_parameter();
  inline void clear_has_parameter();

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int type_;
  ::google::protobuf::int32 time_;
  ::google::protobuf::int32 parameter_;
  friend void  protobuf_AddDesc_events_5fmessage_2eproto();
  friend void protobuf_AssignDesc_events_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_events_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static indigo_event* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// indigo_event

// optional .indigo.pb.indigo_event_type type = 1;
inline bool indigo_event::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void indigo_event::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void indigo_event::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void indigo_event::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::indigo::pb::indigo_event_type indigo_event::type() const {
  // @@protoc_insertion_point(field_get:indigo.pb.indigo_event.type)
  return static_cast< ::indigo::pb::indigo_event_type >(type_);
}
inline void indigo_event::set_type(::indigo::pb::indigo_event_type value) {
  assert(::indigo::pb::indigo_event_type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:indigo.pb.indigo_event.type)
}

// optional int32 time = 2;
inline bool indigo_event::has_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void indigo_event::set_has_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void indigo_event::clear_has_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void indigo_event::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline ::google::protobuf::int32 indigo_event::time() const {
  // @@protoc_insertion_point(field_get:indigo.pb.indigo_event.time)
  return time_;
}
inline void indigo_event::set_time(::google::protobuf::int32 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:indigo.pb.indigo_event.time)
}

// optional int32 parameter = 3;
inline bool indigo_event::has_parameter() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void indigo_event::set_has_parameter() {
  _has_bits_[0] |= 0x00000004u;
}
inline void indigo_event::clear_has_parameter() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void indigo_event::clear_parameter() {
  parameter_ = 0;
  clear_has_parameter();
}
inline ::google::protobuf::int32 indigo_event::parameter() const {
  // @@protoc_insertion_point(field_get:indigo.pb.indigo_event.parameter)
  return parameter_;
}
inline void indigo_event::set_parameter(::google::protobuf::int32 value) {
  set_has_parameter();
  parameter_ = value;
  // @@protoc_insertion_point(field_set:indigo.pb.indigo_event.parameter)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace indigo

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::indigo::pb::indigo_event_type> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_events_5fmessage_2eproto__INCLUDED
