// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpsmodule_message.proto

#ifndef PROTOBUF_gpsmodule_5fmessage_2eproto__INCLUDED
#define PROTOBUF_gpsmodule_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "indigo_message.pb.h"
// @@protoc_insertion_point(includes)

namespace indigo {
namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_gpsmodule_5fmessage_2eproto();
void protobuf_AssignDesc_gpsmodule_5fmessage_2eproto();
void protobuf_ShutdownFile_gpsmodule_5fmessage_2eproto();

class gpsmodule_message;

// ===================================================================

class gpsmodule_message : public ::google::protobuf::MessageLite {
 public:
  gpsmodule_message();
  virtual ~gpsmodule_message();

  gpsmodule_message(const gpsmodule_message& from);

  inline gpsmodule_message& operator=(const gpsmodule_message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const gpsmodule_message& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const gpsmodule_message* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(gpsmodule_message* other);

  // implements Message ----------------------------------------------

  inline gpsmodule_message* New() const { return New(NULL); }

  gpsmodule_message* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const gpsmodule_message& from);
  void MergeFrom(const gpsmodule_message& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(gpsmodule_message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:indigo.pb.gpsmodule_message)
 private:

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_gpsmodule_5fmessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_gpsmodule_5fmessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_gpsmodule_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_gpsmodule_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static gpsmodule_message* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// gpsmodule_message

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace indigo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gpsmodule_5fmessage_2eproto__INCLUDED
