// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: indigo_message.proto

#ifndef PROTOBUF_indigo_5fmessage_2eproto__INCLUDED
#define PROTOBUF_indigo_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace indigo {
namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_indigo_5fmessage_2eproto();
void protobuf_AssignDesc_indigo_5fmessage_2eproto();
void protobuf_ShutdownFile_indigo_5fmessage_2eproto();

class indigo_msg;
class internal_msg;
class indigo_UUID;

// ===================================================================

class indigo_msg : public ::google::protobuf::MessageLite {
 public:
  indigo_msg();
  virtual ~indigo_msg();

  indigo_msg(const indigo_msg& from);

  inline indigo_msg& operator=(const indigo_msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const indigo_msg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const indigo_msg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(indigo_msg* other);

  // implements Message ----------------------------------------------

  inline indigo_msg* New() const { return New(NULL); }

  indigo_msg* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const indigo_msg& from);
  void MergeFrom(const indigo_msg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(indigo_msg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .indigo.pb.indigo_UUID device_id = 1;
  bool has_device_id() const;
  void clear_device_id();
  static const int kDeviceIdFieldNumber = 1;
  const ::indigo::pb::indigo_UUID& device_id() const;
  ::indigo::pb::indigo_UUID* mutable_device_id();
  ::indigo::pb::indigo_UUID* release_device_id();
  void set_allocated_device_id(::indigo::pb::indigo_UUID* device_id);

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(indigo_msg)
  // @@protoc_insertion_point(class_scope:indigo.pb.indigo_msg)
 private:
  inline void set_has_device_id();
  inline void clear_has_device_id();

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::indigo::pb::indigo_UUID* device_id_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_indigo_5fmessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_indigo_5fmessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_indigo_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_indigo_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static indigo_msg* default_instance_;
};
// -------------------------------------------------------------------

class internal_msg : public ::google::protobuf::MessageLite {
 public:
  internal_msg();
  virtual ~internal_msg();

  internal_msg(const internal_msg& from);

  inline internal_msg& operator=(const internal_msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const internal_msg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const internal_msg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(internal_msg* other);

  // implements Message ----------------------------------------------

  inline internal_msg* New() const { return New(NULL); }

  internal_msg* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const internal_msg& from);
  void MergeFrom(const internal_msg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(internal_msg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 id = 1 [default = 0];
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(internal_msg)
  // @@protoc_insertion_point(class_scope:indigo.pb.internal_msg)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_indigo_5fmessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_indigo_5fmessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_indigo_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_indigo_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static internal_msg* default_instance_;
};
// -------------------------------------------------------------------

class indigo_UUID : public ::google::protobuf::MessageLite {
 public:
  indigo_UUID();
  virtual ~indigo_UUID();

  indigo_UUID(const indigo_UUID& from);

  inline indigo_UUID& operator=(const indigo_UUID& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const indigo_UUID& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const indigo_UUID* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(indigo_UUID* other);

  // implements Message ----------------------------------------------

  inline indigo_UUID* New() const { return New(NULL); }

  indigo_UUID* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const indigo_UUID& from);
  void MergeFrom(const indigo_UUID& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(indigo_UUID* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint64 least_significant_bits = 1 [default = 0];
  bool has_least_significant_bits() const;
  void clear_least_significant_bits();
  static const int kLeastSignificantBitsFieldNumber = 1;
  ::google::protobuf::int64 least_significant_bits() const;
  void set_least_significant_bits(::google::protobuf::int64 value);

  // optional sint64 most_significant_bits = 2 [default = 0];
  bool has_most_significant_bits() const;
  void clear_most_significant_bits();
  static const int kMostSignificantBitsFieldNumber = 2;
  ::google::protobuf::int64 most_significant_bits() const;
  void set_most_significant_bits(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:indigo.pb.indigo_UUID)
 private:
  inline void set_has_least_significant_bits();
  inline void clear_has_least_significant_bits();
  inline void set_has_most_significant_bits();
  inline void clear_has_most_significant_bits();

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 least_significant_bits_;
  ::google::protobuf::int64 most_significant_bits_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_indigo_5fmessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_indigo_5fmessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_indigo_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_indigo_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static indigo_UUID* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// indigo_msg

// optional .indigo.pb.indigo_UUID device_id = 1;
inline bool indigo_msg::has_device_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void indigo_msg::set_has_device_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void indigo_msg::clear_has_device_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void indigo_msg::clear_device_id() {
  if (device_id_ != NULL) device_id_->::indigo::pb::indigo_UUID::Clear();
  clear_has_device_id();
}
inline const ::indigo::pb::indigo_UUID& indigo_msg::device_id() const {
  // @@protoc_insertion_point(field_get:indigo.pb.indigo_msg.device_id)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return device_id_ != NULL ? *device_id_ : *default_instance().device_id_;
#else
  return device_id_ != NULL ? *device_id_ : *default_instance_->device_id_;
#endif
}
inline ::indigo::pb::indigo_UUID* indigo_msg::mutable_device_id() {
  set_has_device_id();
  if (device_id_ == NULL) {
    device_id_ = new ::indigo::pb::indigo_UUID;
  }
  // @@protoc_insertion_point(field_mutable:indigo.pb.indigo_msg.device_id)
  return device_id_;
}
inline ::indigo::pb::indigo_UUID* indigo_msg::release_device_id() {
  clear_has_device_id();
  ::indigo::pb::indigo_UUID* temp = device_id_;
  device_id_ = NULL;
  return temp;
}
inline void indigo_msg::set_allocated_device_id(::indigo::pb::indigo_UUID* device_id) {
  delete device_id_;
  device_id_ = device_id;
  if (device_id) {
    set_has_device_id();
  } else {
    clear_has_device_id();
  }
  // @@protoc_insertion_point(field_set_allocated:indigo.pb.indigo_msg.device_id)
}

// -------------------------------------------------------------------

// internal_msg

// optional int32 id = 1 [default = 0];
inline bool internal_msg::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void internal_msg::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void internal_msg::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void internal_msg::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 internal_msg::id() const {
  // @@protoc_insertion_point(field_get:indigo.pb.internal_msg.id)
  return id_;
}
inline void internal_msg::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:indigo.pb.internal_msg.id)
}

// -------------------------------------------------------------------

// indigo_UUID

// optional sint64 least_significant_bits = 1 [default = 0];
inline bool indigo_UUID::has_least_significant_bits() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void indigo_UUID::set_has_least_significant_bits() {
  _has_bits_[0] |= 0x00000001u;
}
inline void indigo_UUID::clear_has_least_significant_bits() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void indigo_UUID::clear_least_significant_bits() {
  least_significant_bits_ = GOOGLE_LONGLONG(0);
  clear_has_least_significant_bits();
}
inline ::google::protobuf::int64 indigo_UUID::least_significant_bits() const {
  // @@protoc_insertion_point(field_get:indigo.pb.indigo_UUID.least_significant_bits)
  return least_significant_bits_;
}
inline void indigo_UUID::set_least_significant_bits(::google::protobuf::int64 value) {
  set_has_least_significant_bits();
  least_significant_bits_ = value;
  // @@protoc_insertion_point(field_set:indigo.pb.indigo_UUID.least_significant_bits)
}

// optional sint64 most_significant_bits = 2 [default = 0];
inline bool indigo_UUID::has_most_significant_bits() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void indigo_UUID::set_has_most_significant_bits() {
  _has_bits_[0] |= 0x00000002u;
}
inline void indigo_UUID::clear_has_most_significant_bits() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void indigo_UUID::clear_most_significant_bits() {
  most_significant_bits_ = GOOGLE_LONGLONG(0);
  clear_has_most_significant_bits();
}
inline ::google::protobuf::int64 indigo_UUID::most_significant_bits() const {
  // @@protoc_insertion_point(field_get:indigo.pb.indigo_UUID.most_significant_bits)
  return most_significant_bits_;
}
inline void indigo_UUID::set_most_significant_bits(::google::protobuf::int64 value) {
  set_has_most_significant_bits();
  most_significant_bits_ = value;
  // @@protoc_insertion_point(field_set:indigo.pb.indigo_UUID.most_significant_bits)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace indigo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_indigo_5fmessage_2eproto__INCLUDED
