// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io_message.proto

#ifndef PROTOBUF_io_5fmessage_2eproto__INCLUDED
#define PROTOBUF_io_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_util.h>
#include "indigo_message.pb.h"
// @@protoc_insertion_point(includes)

namespace indigo {
namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_io_5fmessage_2eproto();
void protobuf_AssignDesc_io_5fmessage_2eproto();
void protobuf_ShutdownFile_io_5fmessage_2eproto();

class io_message;

enum io_message_IO_id {
  io_message_IO_id_DEFAULT = 0,
  io_message_IO_id_POWER1 = 1,
  io_message_IO_id_POWER2 = 2,
  io_message_IO_id_POWER3 = 3,
  io_message_IO_id_POWER4 = 4,
  io_message_IO_id_POWER5 = 5,
  io_message_IO_id_POWER6 = 6,
  io_message_IO_id_POWER7 = 7,
  io_message_IO_id_POWER8 = 8,
  io_message_IO_id_POWER9 = 9,
  io_message_IO_id_POWER10 = 10
};
bool io_message_IO_id_IsValid(int value);
const io_message_IO_id io_message_IO_id_IO_id_MIN = io_message_IO_id_DEFAULT;
const io_message_IO_id io_message_IO_id_IO_id_MAX = io_message_IO_id_POWER10;
const int io_message_IO_id_IO_id_ARRAYSIZE = io_message_IO_id_IO_id_MAX + 1;

// ===================================================================

class io_message : public ::google::protobuf::MessageLite {
 public:
  io_message();
  virtual ~io_message();

  io_message(const io_message& from);

  inline io_message& operator=(const io_message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const io_message& default_instance();

  void Swap(io_message* other);

  // implements Message ----------------------------------------------

  inline io_message* New() const { return New(NULL); }

  io_message* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const io_message& from);
  void MergeFrom(const io_message& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(io_message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  typedef io_message_IO_id IO_id;
  static const IO_id DEFAULT = io_message_IO_id_DEFAULT;
  static const IO_id POWER1 = io_message_IO_id_POWER1;
  static const IO_id POWER2 = io_message_IO_id_POWER2;
  static const IO_id POWER3 = io_message_IO_id_POWER3;
  static const IO_id POWER4 = io_message_IO_id_POWER4;
  static const IO_id POWER5 = io_message_IO_id_POWER5;
  static const IO_id POWER6 = io_message_IO_id_POWER6;
  static const IO_id POWER7 = io_message_IO_id_POWER7;
  static const IO_id POWER8 = io_message_IO_id_POWER8;
  static const IO_id POWER9 = io_message_IO_id_POWER9;
  static const IO_id POWER10 = io_message_IO_id_POWER10;
  static inline bool IO_id_IsValid(int value) {
    return io_message_IO_id_IsValid(value);
  }
  static const IO_id IO_id_MIN =
    io_message_IO_id_IO_id_MIN;
  static const IO_id IO_id_MAX =
    io_message_IO_id_IO_id_MAX;
  static const int IO_id_ARRAYSIZE =
    io_message_IO_id_IO_id_ARRAYSIZE;

  // accessors -------------------------------------------------------

  // required uint32 content = 1;
  bool has_content() const;
  void clear_content();
  static const int kContentFieldNumber = 1;
  ::google::protobuf::uint32 content() const;
  void set_content(::google::protobuf::uint32 value);

  // optional .indigo.pb.io_message.IO_id io_id = 2 [default = DEFAULT];
  bool has_io_id() const;
  void clear_io_id();
  static const int kIoIdFieldNumber = 2;
  ::indigo::pb::io_message_IO_id io_id() const;
  void set_io_id(::indigo::pb::io_message_IO_id value);

  static const int kIoMessageInFieldNumber = 206;
  static ::google::protobuf::internal::ExtensionIdentifier< ::indigo::pb::internal_msg,
      ::google::protobuf::internal::MessageTypeTraits< ::indigo::pb::io_message >, 11, false >
    io_message_in;
  static const int kIoMessageOutFieldNumber = 207;
  static ::google::protobuf::internal::ExtensionIdentifier< ::indigo::pb::indigo_msg,
      ::google::protobuf::internal::MessageTypeTraits< ::indigo::pb::io_message >, 11, false >
    io_message_out;
  // @@protoc_insertion_point(class_scope:indigo.pb.io_message)
 private:
  inline void set_has_content();
  inline void clear_has_content();
  inline void set_has_io_id();
  inline void clear_has_io_id();

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 content_;
  int io_id_;
  friend void  protobuf_AddDesc_io_5fmessage_2eproto();
  friend void protobuf_AssignDesc_io_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_io_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static io_message* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// io_message

// required uint32 content = 1;
inline bool io_message::has_content() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void io_message::set_has_content() {
  _has_bits_[0] |= 0x00000001u;
}
inline void io_message::clear_has_content() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void io_message::clear_content() {
  content_ = 0u;
  clear_has_content();
}
inline ::google::protobuf::uint32 io_message::content() const {
  // @@protoc_insertion_point(field_get:indigo.pb.io_message.content)
  return content_;
}
inline void io_message::set_content(::google::protobuf::uint32 value) {
  set_has_content();
  content_ = value;
  // @@protoc_insertion_point(field_set:indigo.pb.io_message.content)
}

// optional .indigo.pb.io_message.IO_id io_id = 2 [default = DEFAULT];
inline bool io_message::has_io_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void io_message::set_has_io_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void io_message::clear_has_io_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void io_message::clear_io_id() {
  io_id_ = 0;
  clear_has_io_id();
}
inline ::indigo::pb::io_message_IO_id io_message::io_id() const {
  // @@protoc_insertion_point(field_get:indigo.pb.io_message.io_id)
  return static_cast< ::indigo::pb::io_message_IO_id >(io_id_);
}
inline void io_message::set_io_id(::indigo::pb::io_message_IO_id value) {
  assert(::indigo::pb::io_message_IO_id_IsValid(value));
  set_has_io_id();
  io_id_ = value;
  // @@protoc_insertion_point(field_set:indigo.pb.io_message.io_id)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace indigo

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::indigo::pb::io_message_IO_id> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_io_5fmessage_2eproto__INCLUDED
