// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: indigo.proto

#ifndef PROTOBUF_indigo_2eproto__INCLUDED
#define PROTOBUF_indigo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_indigo_2eproto();
void protobuf_AssignDesc_indigo_2eproto();
void protobuf_ShutdownFile_indigo_2eproto();

class indigo_msg;
class indigo_geo;
class indigo_UUID;

enum indigo_event {
  NOTHING = 0
};
bool indigo_event_IsValid(int value);
const indigo_event indigo_event_MIN = NOTHING;
const indigo_event indigo_event_MAX = NOTHING;
const int indigo_event_ARRAYSIZE = indigo_event_MAX + 1;

// ===================================================================

class indigo_msg : public ::google::protobuf::MessageLite {
 public:
  indigo_msg();
  virtual ~indigo_msg();

  indigo_msg(const indigo_msg& from);

  inline indigo_msg& operator=(const indigo_msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const indigo_msg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const indigo_msg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(indigo_msg* other);

  // implements Message ----------------------------------------------

  indigo_msg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const indigo_msg& from);
  void MergeFrom(const indigo_msg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .indigo_UUID device_id = 1;
  inline bool has_device_id() const;
  inline void clear_device_id();
  static const int kDeviceIdFieldNumber = 1;
  inline const ::indigo_UUID& device_id() const;
  inline ::indigo_UUID* mutable_device_id();
  inline ::indigo_UUID* release_device_id();
  inline void set_allocated_device_id(::indigo_UUID* device_id);

  // repeated .indigo_geo coordinates = 3;
  inline int coordinates_size() const;
  inline void clear_coordinates();
  static const int kCoordinatesFieldNumber = 3;
  inline const ::indigo_geo& coordinates(int index) const;
  inline ::indigo_geo* mutable_coordinates(int index);
  inline ::indigo_geo* add_coordinates();
  inline const ::google::protobuf::RepeatedPtrField< ::indigo_geo >&
      coordinates() const;
  inline ::google::protobuf::RepeatedPtrField< ::indigo_geo >*
      mutable_coordinates();

  // repeated .indigo_event events = 4;
  inline int events_size() const;
  inline void clear_events();
  static const int kEventsFieldNumber = 4;
  inline ::indigo_event events(int index) const;
  inline void set_events(int index, ::indigo_event value);
  inline void add_events(::indigo_event value);
  inline const ::google::protobuf::RepeatedField<int>& events() const;
  inline ::google::protobuf::RepeatedField<int>* mutable_events();

  // @@protoc_insertion_point(class_scope:indigo_msg)
 private:
  inline void set_has_device_id();
  inline void clear_has_device_id();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::indigo_UUID* device_id_;
  ::google::protobuf::RepeatedPtrField< ::indigo_geo > coordinates_;
  ::google::protobuf::RepeatedField<int> events_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_indigo_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_indigo_2eproto();
  #endif
  friend void protobuf_AssignDesc_indigo_2eproto();
  friend void protobuf_ShutdownFile_indigo_2eproto();

  void InitAsDefaultInstance();
  static indigo_msg* default_instance_;
};
// -------------------------------------------------------------------

class indigo_geo : public ::google::protobuf::MessageLite {
 public:
  indigo_geo();
  virtual ~indigo_geo();

  indigo_geo(const indigo_geo& from);

  inline indigo_geo& operator=(const indigo_geo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const indigo_geo& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const indigo_geo* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(indigo_geo* other);

  // implements Message ----------------------------------------------

  indigo_geo* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const indigo_geo& from);
  void MergeFrom(const indigo_geo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double longitude = 1;
  inline bool has_longitude() const;
  inline void clear_longitude();
  static const int kLongitudeFieldNumber = 1;
  inline double longitude() const;
  inline void set_longitude(double value);

  // required double latitude = 2;
  inline bool has_latitude() const;
  inline void clear_latitude();
  static const int kLatitudeFieldNumber = 2;
  inline double latitude() const;
  inline void set_latitude(double value);

  // required int32 unixtime = 3;
  inline bool has_unixtime() const;
  inline void clear_unixtime();
  static const int kUnixtimeFieldNumber = 3;
  inline ::google::protobuf::int32 unixtime() const;
  inline void set_unixtime(::google::protobuf::int32 value);

  // optional int32 speed_kmh = 4 [default = 0];
  inline bool has_speed_kmh() const;
  inline void clear_speed_kmh();
  static const int kSpeedKmhFieldNumber = 4;
  inline ::google::protobuf::int32 speed_kmh() const;
  inline void set_speed_kmh(::google::protobuf::int32 value);

  // optional int32 track = 5 [default = 0];
  inline bool has_track() const;
  inline void clear_track();
  static const int kTrackFieldNumber = 5;
  inline ::google::protobuf::int32 track() const;
  inline void set_track(::google::protobuf::int32 value);

  // optional int32 satellites_used = 6 [default = 0];
  inline bool has_satellites_used() const;
  inline void clear_satellites_used();
  static const int kSatellitesUsedFieldNumber = 6;
  inline ::google::protobuf::int32 satellites_used() const;
  inline void set_satellites_used(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:indigo_geo)
 private:
  inline void set_has_longitude();
  inline void clear_has_longitude();
  inline void set_has_latitude();
  inline void clear_has_latitude();
  inline void set_has_unixtime();
  inline void clear_has_unixtime();
  inline void set_has_speed_kmh();
  inline void clear_has_speed_kmh();
  inline void set_has_track();
  inline void clear_has_track();
  inline void set_has_satellites_used();
  inline void clear_has_satellites_used();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double longitude_;
  double latitude_;
  ::google::protobuf::int32 unixtime_;
  ::google::protobuf::int32 speed_kmh_;
  ::google::protobuf::int32 track_;
  ::google::protobuf::int32 satellites_used_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_indigo_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_indigo_2eproto();
  #endif
  friend void protobuf_AssignDesc_indigo_2eproto();
  friend void protobuf_ShutdownFile_indigo_2eproto();

  void InitAsDefaultInstance();
  static indigo_geo* default_instance_;
};
// -------------------------------------------------------------------

class indigo_UUID : public ::google::protobuf::MessageLite {
 public:
  indigo_UUID();
  virtual ~indigo_UUID();

  indigo_UUID(const indigo_UUID& from);

  inline indigo_UUID& operator=(const indigo_UUID& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const indigo_UUID& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const indigo_UUID* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(indigo_UUID* other);

  // implements Message ----------------------------------------------

  indigo_UUID* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const indigo_UUID& from);
  void MergeFrom(const indigo_UUID& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint64 least_significant_bits = 1 [default = 0];
  inline bool has_least_significant_bits() const;
  inline void clear_least_significant_bits();
  static const int kLeastSignificantBitsFieldNumber = 1;
  inline ::google::protobuf::int64 least_significant_bits() const;
  inline void set_least_significant_bits(::google::protobuf::int64 value);

  // optional sint64 most_significant_bits = 2 [default = 0];
  inline bool has_most_significant_bits() const;
  inline void clear_most_significant_bits();
  static const int kMostSignificantBitsFieldNumber = 2;
  inline ::google::protobuf::int64 most_significant_bits() const;
  inline void set_most_significant_bits(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:indigo_UUID)
 private:
  inline void set_has_least_significant_bits();
  inline void clear_has_least_significant_bits();
  inline void set_has_most_significant_bits();
  inline void clear_has_most_significant_bits();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 least_significant_bits_;
  ::google::protobuf::int64 most_significant_bits_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_indigo_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_indigo_2eproto();
  #endif
  friend void protobuf_AssignDesc_indigo_2eproto();
  friend void protobuf_ShutdownFile_indigo_2eproto();

  void InitAsDefaultInstance();
  static indigo_UUID* default_instance_;
};
// ===================================================================


// ===================================================================

// indigo_msg

// optional .indigo_UUID device_id = 1;
inline bool indigo_msg::has_device_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void indigo_msg::set_has_device_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void indigo_msg::clear_has_device_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void indigo_msg::clear_device_id() {
  if (device_id_ != NULL) device_id_->::indigo_UUID::Clear();
  clear_has_device_id();
}
inline const ::indigo_UUID& indigo_msg::device_id() const {
  // @@protoc_insertion_point(field_get:indigo_msg.device_id)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return device_id_ != NULL ? *device_id_ : *default_instance().device_id_;
#else
  return device_id_ != NULL ? *device_id_ : *default_instance_->device_id_;
#endif
}
inline ::indigo_UUID* indigo_msg::mutable_device_id() {
  set_has_device_id();
  if (device_id_ == NULL) device_id_ = new ::indigo_UUID;
  // @@protoc_insertion_point(field_mutable:indigo_msg.device_id)
  return device_id_;
}
inline ::indigo_UUID* indigo_msg::release_device_id() {
  clear_has_device_id();
  ::indigo_UUID* temp = device_id_;
  device_id_ = NULL;
  return temp;
}
inline void indigo_msg::set_allocated_device_id(::indigo_UUID* device_id) {
  delete device_id_;
  device_id_ = device_id;
  if (device_id) {
    set_has_device_id();
  } else {
    clear_has_device_id();
  }
  // @@protoc_insertion_point(field_set_allocated:indigo_msg.device_id)
}

// repeated .indigo_geo coordinates = 3;
inline int indigo_msg::coordinates_size() const {
  return coordinates_.size();
}
inline void indigo_msg::clear_coordinates() {
  coordinates_.Clear();
}
inline const ::indigo_geo& indigo_msg::coordinates(int index) const {
  // @@protoc_insertion_point(field_get:indigo_msg.coordinates)
  return coordinates_.Get(index);
}
inline ::indigo_geo* indigo_msg::mutable_coordinates(int index) {
  // @@protoc_insertion_point(field_mutable:indigo_msg.coordinates)
  return coordinates_.Mutable(index);
}
inline ::indigo_geo* indigo_msg::add_coordinates() {
  // @@protoc_insertion_point(field_add:indigo_msg.coordinates)
  return coordinates_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::indigo_geo >&
indigo_msg::coordinates() const {
  // @@protoc_insertion_point(field_list:indigo_msg.coordinates)
  return coordinates_;
}
inline ::google::protobuf::RepeatedPtrField< ::indigo_geo >*
indigo_msg::mutable_coordinates() {
  // @@protoc_insertion_point(field_mutable_list:indigo_msg.coordinates)
  return &coordinates_;
}

// repeated .indigo_event events = 4;
inline int indigo_msg::events_size() const {
  return events_.size();
}
inline void indigo_msg::clear_events() {
  events_.Clear();
}
inline ::indigo_event indigo_msg::events(int index) const {
  // @@protoc_insertion_point(field_get:indigo_msg.events)
  return static_cast< ::indigo_event >(events_.Get(index));
}
inline void indigo_msg::set_events(int index, ::indigo_event value) {
  assert(::indigo_event_IsValid(value));
  events_.Set(index, value);
  // @@protoc_insertion_point(field_set:indigo_msg.events)
}
inline void indigo_msg::add_events(::indigo_event value) {
  assert(::indigo_event_IsValid(value));
  events_.Add(value);
  // @@protoc_insertion_point(field_add:indigo_msg.events)
}
inline const ::google::protobuf::RepeatedField<int>&
indigo_msg::events() const {
  // @@protoc_insertion_point(field_list:indigo_msg.events)
  return events_;
}
inline ::google::protobuf::RepeatedField<int>*
indigo_msg::mutable_events() {
  // @@protoc_insertion_point(field_mutable_list:indigo_msg.events)
  return &events_;
}

// -------------------------------------------------------------------

// indigo_geo

// required double longitude = 1;
inline bool indigo_geo::has_longitude() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void indigo_geo::set_has_longitude() {
  _has_bits_[0] |= 0x00000001u;
}
inline void indigo_geo::clear_has_longitude() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void indigo_geo::clear_longitude() {
  longitude_ = 0;
  clear_has_longitude();
}
inline double indigo_geo::longitude() const {
  // @@protoc_insertion_point(field_get:indigo_geo.longitude)
  return longitude_;
}
inline void indigo_geo::set_longitude(double value) {
  set_has_longitude();
  longitude_ = value;
  // @@protoc_insertion_point(field_set:indigo_geo.longitude)
}

// required double latitude = 2;
inline bool indigo_geo::has_latitude() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void indigo_geo::set_has_latitude() {
  _has_bits_[0] |= 0x00000002u;
}
inline void indigo_geo::clear_has_latitude() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void indigo_geo::clear_latitude() {
  latitude_ = 0;
  clear_has_latitude();
}
inline double indigo_geo::latitude() const {
  // @@protoc_insertion_point(field_get:indigo_geo.latitude)
  return latitude_;
}
inline void indigo_geo::set_latitude(double value) {
  set_has_latitude();
  latitude_ = value;
  // @@protoc_insertion_point(field_set:indigo_geo.latitude)
}

// required int32 unixtime = 3;
inline bool indigo_geo::has_unixtime() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void indigo_geo::set_has_unixtime() {
  _has_bits_[0] |= 0x00000004u;
}
inline void indigo_geo::clear_has_unixtime() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void indigo_geo::clear_unixtime() {
  unixtime_ = 0;
  clear_has_unixtime();
}
inline ::google::protobuf::int32 indigo_geo::unixtime() const {
  // @@protoc_insertion_point(field_get:indigo_geo.unixtime)
  return unixtime_;
}
inline void indigo_geo::set_unixtime(::google::protobuf::int32 value) {
  set_has_unixtime();
  unixtime_ = value;
  // @@protoc_insertion_point(field_set:indigo_geo.unixtime)
}

// optional int32 speed_kmh = 4 [default = 0];
inline bool indigo_geo::has_speed_kmh() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void indigo_geo::set_has_speed_kmh() {
  _has_bits_[0] |= 0x00000008u;
}
inline void indigo_geo::clear_has_speed_kmh() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void indigo_geo::clear_speed_kmh() {
  speed_kmh_ = 0;
  clear_has_speed_kmh();
}
inline ::google::protobuf::int32 indigo_geo::speed_kmh() const {
  // @@protoc_insertion_point(field_get:indigo_geo.speed_kmh)
  return speed_kmh_;
}
inline void indigo_geo::set_speed_kmh(::google::protobuf::int32 value) {
  set_has_speed_kmh();
  speed_kmh_ = value;
  // @@protoc_insertion_point(field_set:indigo_geo.speed_kmh)
}

// optional int32 track = 5 [default = 0];
inline bool indigo_geo::has_track() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void indigo_geo::set_has_track() {
  _has_bits_[0] |= 0x00000010u;
}
inline void indigo_geo::clear_has_track() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void indigo_geo::clear_track() {
  track_ = 0;
  clear_has_track();
}
inline ::google::protobuf::int32 indigo_geo::track() const {
  // @@protoc_insertion_point(field_get:indigo_geo.track)
  return track_;
}
inline void indigo_geo::set_track(::google::protobuf::int32 value) {
  set_has_track();
  track_ = value;
  // @@protoc_insertion_point(field_set:indigo_geo.track)
}

// optional int32 satellites_used = 6 [default = 0];
inline bool indigo_geo::has_satellites_used() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void indigo_geo::set_has_satellites_used() {
  _has_bits_[0] |= 0x00000020u;
}
inline void indigo_geo::clear_has_satellites_used() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void indigo_geo::clear_satellites_used() {
  satellites_used_ = 0;
  clear_has_satellites_used();
}
inline ::google::protobuf::int32 indigo_geo::satellites_used() const {
  // @@protoc_insertion_point(field_get:indigo_geo.satellites_used)
  return satellites_used_;
}
inline void indigo_geo::set_satellites_used(::google::protobuf::int32 value) {
  set_has_satellites_used();
  satellites_used_ = value;
  // @@protoc_insertion_point(field_set:indigo_geo.satellites_used)
}

// -------------------------------------------------------------------

// indigo_UUID

// optional sint64 least_significant_bits = 1 [default = 0];
inline bool indigo_UUID::has_least_significant_bits() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void indigo_UUID::set_has_least_significant_bits() {
  _has_bits_[0] |= 0x00000001u;
}
inline void indigo_UUID::clear_has_least_significant_bits() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void indigo_UUID::clear_least_significant_bits() {
  least_significant_bits_ = GOOGLE_LONGLONG(0);
  clear_has_least_significant_bits();
}
inline ::google::protobuf::int64 indigo_UUID::least_significant_bits() const {
  // @@protoc_insertion_point(field_get:indigo_UUID.least_significant_bits)
  return least_significant_bits_;
}
inline void indigo_UUID::set_least_significant_bits(::google::protobuf::int64 value) {
  set_has_least_significant_bits();
  least_significant_bits_ = value;
  // @@protoc_insertion_point(field_set:indigo_UUID.least_significant_bits)
}

// optional sint64 most_significant_bits = 2 [default = 0];
inline bool indigo_UUID::has_most_significant_bits() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void indigo_UUID::set_has_most_significant_bits() {
  _has_bits_[0] |= 0x00000002u;
}
inline void indigo_UUID::clear_has_most_significant_bits() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void indigo_UUID::clear_most_significant_bits() {
  most_significant_bits_ = GOOGLE_LONGLONG(0);
  clear_has_most_significant_bits();
}
inline ::google::protobuf::int64 indigo_UUID::most_significant_bits() const {
  // @@protoc_insertion_point(field_get:indigo_UUID.most_significant_bits)
  return most_significant_bits_;
}
inline void indigo_UUID::set_most_significant_bits(::google::protobuf::int64 value) {
  set_has_most_significant_bits();
  most_significant_bits_ = value;
  // @@protoc_insertion_point(field_set:indigo_UUID.most_significant_bits)
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_indigo_2eproto__INCLUDED
